server:
  port: 9004
spring:
  application:
    name: input-stream-service
  rabbitmq:
    addresses: 10.0.200.52
    username: toby
    password: toby
  cloud:
    stream:
      bindings:
        input:
          destination: com.lcy
      binders:
        defaultRabbit:
          type: rabbit