server:
  port: 10000
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TobyLilcy/config-service.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #向注册中心注册服务id